title: Feature Request
description: Describe a feature you would like us to add or improve
labels: [ "cX", "feature" ]
body:
  - type: markdown
    attributes:
      label: Description
      description: A clear and concise description of the idea
    validations:
      required: true
  - type: markdown
    attributes:
      label: Example
      description: |
        A simple example of the new feature in action (include PHP code, Twig variable, YAML config, etc.)
        If the new feature changes an existing feature, include a simple before/after comparison.


